import"./assets/styles-XcnS6RU7.js";import{a as f,i as n}from"./assets/vendor-4yCzdkXl.js";async function M(){const t="https://dummyjson.com/products/category-list";try{return(await f.get(t)).data}catch(e){throw console.error("Помилка під час отримання категорій:",e.message),e}}async function q(t){const r=`https://dummyjson.com/products/category/${t}?limit=12&skip=0`;try{return(await f.get(r)).data.products}catch(s){throw console.error("Помилка під час отримання продуктів:",s.message),s}}async function _(){const e="https://dummyjson.com/products?limit=12&skip=0";try{return(await f.get(e)).data.products}catch(r){throw console.error("Помилка під час отримання продуктів:",r.message),r}}async function C(t){const e=await fetch(`https://dummyjson.com/products/${t}`);if(!e.ok)throw new Error("Failed to fetch product");return await e.json()}async function $(t){const e=`https://dummyjson.com/products/search?q=${encodeURIComponent(t)}&limit=12`;try{return(await f.get(e)).data.products}catch(r){throw console.error("Помилка під час пошуку продуктів:",r.message),r}}const o={formEl:document.querySelector(".search-form"),inputEl:document.querySelector(".search-form__input"),clearSearchBtnEl:document.querySelector(".search-form__btn-clear"),searchBtnEl:document.querySelector(".search-form__btn"),categoriesListEl:document.querySelector(".categories"),productsListEl:document.querySelector(".products"),loadMoreBtn:document.querySelector(".btn"),loaderEl:document.querySelector(".loader"),modalEl:document.querySelector(".modal"),modalCloseBtnEl:document.querySelector(".modal__close-btn"),modalContentEl:document.querySelector(".modal__content"),modalOverlayEl:document.querySelector(".modal__overlay")};let i=[];function v(){localStorage.setItem("cards",JSON.stringify(i))}function E(t){I(t),o.modalEl.classList.add("modal--is-open")}function b(){o.modalEl.classList.remove("modal--is-open");const t=o.modalContentEl.querySelector(".modal-product");t&&(t.innerHTML="")}o.modalEl.addEventListener("click",t=>{(t.target.classList.contains("modal__close-btn")||t.target===o.modalEl)&&b()});document.addEventListener("keydown",t=>{t.key==="Escape"&&b()});const S=document.querySelector(".products");function B(t){return t.map(e=>`<li class="categories__item">
   <button class="categories__btn" type="button" data-category="${e}">${e}</button>
 </li>
`).join("")}function y(t){return t.map(e=>`<li class="products__item" data-id="${e.id}">
                  <img class="products__image" src="${e.thumbnail}" alt="${e.title}"/>
                   <p class="products__title">${e.title}</p>
                    <p class="products__brand"><span class="products__brand--bold">Brand: </span>${e.brand}</p>
                    <p class="products__category">Category: ${e.category}</p>
                    <p class="products__price">Price: ${e.price} $</p>
 </li>
`).join("")}async function k(){o.categoriesListEl.classList.add("hidden"),o.productsListEl.classList.add("hidden"),document.querySelector(".not-found").classList.add("is-hidden");try{const t=await M(),e=await _(),r=B(t),s=y(e),c=document.querySelector(".categories"),u=document.querySelector(".products");c.insertAdjacentHTML("beforeend",r),e.length===0?document.querySelector(".not-found").classList.remove("is-hidden"):(u.insertAdjacentHTML("beforeend",s),o.productsListEl.classList.remove("hidden")),l(),o.categoriesListEl.classList.remove("hidden"),u.addEventListener("click",L=>{const p=L.target.closest(".product-card");if(!p)return;const d=p.dataset.id;d&&E(d)})}catch(t){console.error("Помилка при ініціалізації сторінки:",t.message)}finally{a()}}function P(){S.innerHTML=""}function l(){o.loadMoreBtn&&(o.loadMoreBtn.classList.remove("is-hidden"),o.loadMoreBtn.classList.add("is-visible"))}function m(){o.loadMoreBtn&&(o.loadMoreBtn.classList.add("is-hidden"),o.loadMoreBtn.classList.remove("is-visible"))}function h(){const t=document.querySelector(".loader");t&&(t.classList.remove("is-hidden"),t.classList.add("is-visible"))}function a(){const t=document.querySelector(".loader");t&&(t.classList.add("is-hidden"),t.classList.remove("is-visible"))}function T(){document.querySelectorAll(".loader-page").forEach(t=>{t.classList.remove("is-hidden"),t.classList.add("is-visible")})}function A(){document.querySelectorAll(".loader-page").forEach(t=>{t.classList.add("is-hidden"),t.classList.remove("is-visible")})}async function j(t){try{const e=await _(),r=y(e);S.insertAdjacentHTML("beforeend",r)}catch(e){console.error("Error fetching products:",e.message)}}o.productsListEl.addEventListener("click",t=>{const e=t.target.closest(".products__item");if(!e)return;const r=e.dataset.id,s=i.find(c=>c.id===Number(r));s&&E(s)});async function I(t){const{images:e,title:r,description:s,tags:c,shippingInformation:u,returnPolicy:L,price:p}=t,d=o.modalContentEl.querySelector(".modal-product");if(!d){console.warn("Element .modal-product not found");return}d.innerHTML=`
    <img class="modal-product__img" src="${e[0]}" alt="${r}" />
    <div class="modal-product__content">
      <p class="modal-product__title">${r}</p>
      <ul class="modal-product__tags">${c==null?void 0:c.map(w=>`<li>${w}</li>`).join("")}</ul>
      <p class="modal-product__description">${s}</p>
      <p class="modal-product__shipping-information">Shipping: ${u||"Not specified"}</p>
      <p class="modal-product__return-policy">Return Policy: ${L||"Not specified"}</p>
      <p class="modal-product__price">Price: ${p}$</p>
      <button class="modal-product__buy-btn" type="button">Buy</button>
    </div>
  `}document.addEventListener("DOMContentLoaded",async()=>{T(),await new Promise(t=>setTimeout(t,100)),k(),A(),document.getElementById("content").classList.remove("is-hidden")});let N="",g=1;o.categoriesListEl.addEventListener("click",async t=>{if(t.target===t.currentTarget)return;const e=t.target.dataset.category;if(!e)return;o.categoriesListEl.querySelectorAll(".categories__btn").forEach(s=>s.classList.remove("categories__btn--active")),t.target.classList.add("categories__btn--active"),g=1,P(),m(),h();try{const s=await q(e);if(s.length===0){n.error({title:"Error",message:"No products found in this category.",position:"topCenter"}),a();return}i.length=0,i.push(...s),v();const c=y(s);o.productsListEl.insertAdjacentHTML("beforeend",c),l()}catch(s){console.error("Error fetching products:",s.message)}finally{a()}});o.formEl.addEventListener("submit",async t=>{t.preventDefault();const e=o.inputEl.value.trim();if(!e){n.error({title:"Error",message:"Please enter a search query.",position:"topCenter"});return}P(),m(),h();try{const r=await $(e);if(!r||r.length===0){n.error({title:"Error",message:"No products found.",position:"topCenter"});return}i.length=0,i.push(...r),v();const s=y(r);o.productsListEl.insertAdjacentHTML("beforeend",s),l()}catch(r){console.error("Search error:",r.message),n.error({title:"Error",message:"Something went wrong. Please try again.",position:"topCenter"})}finally{a(),o.formEl.reset()}});o.loadMoreBtn.addEventListener("click",async()=>{g+=1,h(),m();const t=Date.now(),e=2e3;try{const r=await _(N,g);if(r.length===0){n.error({title:"Error",message:"No more products found.",position:"topCenter"}),m();return}j(r)}catch{n.error({title:"Error",message:"Failed to load products.",position:"topCenter"})}finally{const r=Date.now()-t,s=e-r;s>0?setTimeout(()=>{l(),a()},s):(a(),l())}});o.clearSearchBtnEl.addEventListener("click",()=>{o.inputEl.value="",g=1,n.info({title:"Info",message:"Search cleared.",position:"topCenter"})});o.productsListEl.addEventListener("click",async t=>{const e=t.target.closest(".products__item");if(!e)return;const r=e.dataset.id;if(r)try{h();const s=await C(r);E(s)}catch(s){n.error({title:"Error",message:"Failed to load product details.",position:"topCenter"}),console.error("Error loading product:",s)}finally{a()}});
//# sourceMappingURL=index.js.map
