import"./assets/styles-B7k7pSwN.js";import{a as p,i as c}from"./assets/vendor-4yCzdkXl.js";async function E(){const t="https://dummyjson.com/products/category-list";try{return(await p.get(t)).data}catch(e){throw console.error("Помилка під час отримання категорій:",e.message),e}}async function L(t){const r=`https://dummyjson.com/products/category/${t}?limit=12&skip=0`;try{return(await p.get(r)).data.products}catch(s){throw console.error("Помилка під час отримання продуктів:",s.message),s}}async function u(){const e="https://dummyjson.com/products?limit=12&skip=0";try{return(await p.get(e)).data.products}catch(r){throw console.error("Помилка під час отримання продуктів:",r.message),r}}const o={formEl:document.querySelector(".search-form"),inputEl:document.querySelector(".search-form__input"),clearSearchBtnEl:document.querySelector(".search-form__btn-clear"),searchBtnEl:document.querySelector(".search-form__btn"),categoriesListEl:document.querySelector(".categories"),productsListEl:document.querySelector(".products"),loadMoreBtn:document.querySelector(".btn"),loaderEl:document.querySelector(".loader"),modalEl:document.querySelector(".modal"),modalCloseBtnEl:document.querySelector(".modal__close-btn"),modalContentEl:document.querySelector(".modal__content"),modalOverlayEl:document.querySelector(".modal__overlay")},f=document.querySelector(".products");function M(t){return t.map(e=>`<li class="categories__item">
   <button class="categories__btn" type="button" data-category="${e}">${e}</button>
 </li>
`).join("")}function m(t){return t.map(e=>`<li class="products__item" data-id="${e.id}">
                  <img class="products__image" src="${e.thumbnail}" alt="${e.title}"/>
                   <p class="products__title">${e.title}</p>
                    <p class="products__brand"><span class="products__brand--bold">Brand: </span>${e.brand}</p>
                    <p class="products__category">Category: ${e.category}</p>
                    <p class="products__price">Price: ${e.price} $</p>
 </li>
`).join("")}async function b(){try{const t=await E(),e=await u(),r=M(t),s=m(e),h=document.querySelector(".categories"),_=document.querySelector(".products");h.insertAdjacentHTML("beforeend",r),_.insertAdjacentHTML("beforeend",s),i()}catch(t){console.error("Помилка при ініціалізації сторінки:",t.message)}}function g(){f.innerHTML=""}function i(){o.loadMoreBtn&&(o.loadMoreBtn.classList.remove("is-hidden"),o.loadMoreBtn.classList.add("is-visible"))}function l(){o.loadMoreBtn&&(o.loadMoreBtn.classList.add("is-hidden"),o.loadMoreBtn.classList.remove("is-visible"))}function y(){const t=document.querySelector(".loader");t&&(t.classList.remove("is-hidden"),t.classList.add("is-visible"))}function n(){const t=document.querySelector(".loader");t&&(t.classList.add("is-hidden"),t.classList.remove("is-visible"))}async function S(t){try{const e=await u(),r=m(e);f.insertAdjacentHTML("beforeend",r)}catch(e){console.error("Error fetching products:",e.message)}}b();let d="",a=1;const P=12;o.categoriesListEl.addEventListener("click",async t=>{if(t.target===t.currentTarget)return;const e=t.target.dataset.category;if(e){a=1,g(),l(),y();try{const r=await L(e);if(r.length===0){c.error({title:"Error",message:"No products found in this category.",position:"topCenter"}),n();return}const s=m(r);o.productsListEl.insertAdjacentHTML("beforeend",s),i()}catch(r){console.error("Error fetching products:",r.message)}finally{n()}}});o.formEl.addEventListener("submit",async t=>{if(t.preventDefault(),d=o.inputEl.value.trim(),!d){c.error({title:"Error",message:"Please enter a search query.",position:"topCenter"});return}a=1,g(),y();try{const e=await u(d,a,P);if(e.length===0){c.error({title:"Error",message:"No products found.",position:"topCenter"}),n();return}const r=m(e);o.productsListEl.insertAdjacentHTML("beforeend",r),i()}catch(e){console.error("Error fetching products:",e.message)}finally{n(),o.formEl.reset()}});o.loadMoreBtn.addEventListener("click",async()=>{a+=1,y(),l();const t=Date.now(),e=2e3;try{const r=await u(d,a);if(r.length===0){c.error({title:"Error",message:"No more products found.",position:"topCenter"}),l();return}S(r)}catch{c.error({title:"Error",message:"Failed to load products.",position:"topCenter"})}finally{const r=Date.now()-t,s=e-r;s>0?setTimeout(()=>{i(),n()},s):(n(),i())}});o.clearSearchBtnEl.addEventListener("click",()=>{o.inputEl.value="",g(),l(),a=1,c.info({title:"Info",message:"Search cleared.",position:"topCenter"})});
//# sourceMappingURL=index.js.map
